resources:
    - truecharts.yaml
    - actions-runner-controller.yaml
    - authentik.yaml
    - backube.yaml
    - bitnami.yaml
    - bjw-s.yaml
    - cilium.yaml
    - cloudnative-pg.yaml
    - coredns.yaml
    - crossplane.yaml
    - crowdsec.yaml
    - crunchydata.yaml
    - csi-driver-nfs.yaml
    - deliveryhero.yaml
    - democratic-csi.yaml
    - descheduler.yaml
    - dysnix.yaml
    - emqx.yaml
    - external-dns.yaml
    - external-secrets.yaml
    - fairwinds.yaml
    - fluent-bit.yaml
    - grafana.yaml
    - infracloudio.yaml
    - ingress-nginx.yaml
    - intel.yaml
    - jaegertracing.yaml
    - jetstack.yaml
    - k8s-at-home.yaml
    - kubernetes-sigs-metrics-server.yaml
    - kyverno.yaml
    - lwolf.yaml
    - metallb.yaml
    - metrics-server.yaml
    - node-feature-discovery.yaml
    - nvidia.yaml
    - openebs.yaml
    - piraeus.yaml
    - postfinance.yaml
    - prometheus-community.yaml
    - rook-ceph.yaml
    - runix.yaml
    - spegel.yaml
    - stakater.yaml
    - stevehipwell.yaml
    - tf-controller.yaml
    - traefik.yaml
    - weave-gitops.yaml
